name: Build and Push
on:
  push:
    tags: 'v*.*.*'
jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Authenticate to Google Cloud
        id: auth-gcp
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/1039850042661/locations/global/workloadIdentityPools/github-pool-prod/providers/github-provider-prod
          service_account: artifact-registry-pusher@proj-mission-control-80492.iam.gserviceaccount.com

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: us-east1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth-gcp.outputs.access_token }}

      - name: Tag Docker image and push to Google Artifact Registry
        id: build-push-tag
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             us-east1-docker.pkg.dev/proj-mission-control-80492/core/scoreboard:${{ steps.get-tag.outputs.short_ref }}
             us-east1-docker.pkg.dev/proj-mission-control-80492/core/scoreboard:latest